import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import { NextAuthProvider } from "./lib/next-auth/provider";
import "bootstrap/dist/css/bootstrap.css";
import { Suspense } from "react";
import Loading from "../../Loading";
import "bootstrap-icons/font/bootstrap-icons.css";
import ToasterProvider from "./components/toaster/ToasterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <body className={inter.className}>
          <NextAuthProvider>
            <Suspense fallback={<Loading />}>
              {children}
              <ToasterProvider />
            </Suspense>
          </NextAuthProvider>
        </body>
      </head>
    </html>
  );
}
